// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb1DS2F8GRUVF9OYNIeCxTzX1lrz2_kp0',
    appId: '1:65063242216:web:77ac5ea3305bb706277c5d',
    messagingSenderId: '65063242216',
    projectId: 'wear2wear-fd5eb',
    authDomain: 'wear2wear-fd5eb.firebaseapp.com',
    storageBucket: 'wear2wear-fd5eb.firebasestorage.app',
    measurementId: 'G-BSP0M40JWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YKLyNCy3Ok5YdAlsUlZZa8OsbwKOoyw',
    appId: '1:65063242216:android:51b8dc173bcd7021277c5d',
    messagingSenderId: '65063242216',
    projectId: 'wear2wear-fd5eb',
    storageBucket: 'wear2wear-fd5eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCls4A8j67pZNVLnEa5h1suPU4uuvD630M',
    appId: '1:65063242216:ios:aff100dbb616d4f7277c5d',
    messagingSenderId: '65063242216',
    projectId: 'wear2wear-fd5eb',
    storageBucket: 'wear2wear-fd5eb.firebasestorage.app',
    iosBundleId: 'com.example.dwqdqw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCls4A8j67pZNVLnEa5h1suPU4uuvD630M',
    appId: '1:65063242216:ios:aff100dbb616d4f7277c5d',
    messagingSenderId: '65063242216',
    projectId: 'wear2wear-fd5eb',
    storageBucket: 'wear2wear-fd5eb.firebasestorage.app',
    iosBundleId: 'com.example.dwqdqw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb1DS2F8GRUVF9OYNIeCxTzX1lrz2_kp0',
    appId: '1:65063242216:web:f16e490e9bf62b11277c5d',
    messagingSenderId: '65063242216',
    projectId: 'wear2wear-fd5eb',
    authDomain: 'wear2wear-fd5eb.firebaseapp.com',
    storageBucket: 'wear2wear-fd5eb.firebasestorage.app',
    measurementId: 'G-CF6SM9D6FX',
  );
}
